### ISSUE TITLE
Fallo al iniciar sesión Github

### ISSUE THREAD

**Issue by julsoutos** [decide-part-andarax-2/decide#105]
Se produce un fallo al intentar hacer el login con github.

El error se produce en cualquier navegador (Firefox, Chromium o Opera) . Se han seguido los siguientes pasos:

1.- Descargamos la rama develop.
2.- Nos metemos en cualquier login de booth creando una voting anteriormente.
3.- Abrimos el panel de admin para comprobar que se crean los usuarios. 
4.-Le damos a hacer autenticación por github.
5.- Devuelve un error. 

La traza del error es : AuthAlreadyAssociated at /authentication/social-auth/complete/github/

El error debe ser porque detecta que ya estaba iniciado sesión.

**Comment by PabloRodriguezGarrido11** [comment]
Este error se debe a que la aplicación social_django_app_social detecta que ya existe una sesión abierta en el sistema, que se corresponde con el inicio de sesión realizado en el paso 3. Por lo tanto, para solucionar esto, previamente a realizar la autenticación mediante Github, debes cerrar sesión como administrador, de forma que no exista esta sesión persistente en el sistema.

**Comment by julsoutos** [comment]
De esta forma sí que funciona. Se da por solucionada la incidencia entonces.
