### ISSUE TITLE
Comportamiento incorrecto en las pruebas

### ISSUE THREAD

**Issue by julsoutos** [decide-part-andarax-2/decide#131]
Al ejecutar las pruebas en local, algunas relacionadas con selenium hace que el navegador se abra y las ejecute en lugar de hacerse en segundo plano.

Los pasos seguidos son los siguientes:
1.- Nos clonamos la rama de develop.
2.- Ejecutamos el comando "python manage.py test authentication".
3.- Vemos como nos van saliendo algunas de las pruebas ejecutándose, cuando el comportamiento debería ser que se ejecutaran en segundo plano.

El error debe estar en los archivos de test de selenium del módulo de autenticación, tras haberse cambiado el estilo del css de la página de login.

**Comment by JulianGR** [comment]
Este es el comportamiento que se espera, ya que para las pruebas de mi incremento (Google OAuth) es necesario para hacer debug y demotrar que efectivamente Google detecta las pruebas como bot y las bloquea. 

Para el incremento de Github OAuth también hizo falta, ya que al cambiar el CSS las pruebas fallaban, y si se incluía este comportamiento, las pruebas pasaban

**Comment by julsoutos** [comment]
De acuerdo, por ese motivo entonces se aceptará esa excepción y se permitirá que las pruebas las ejecute en primer plano el navegador, ya que no son más de 4 pruebas.
