### ISSUE TITLE
Error 404 al acceder a una votación

### ISSUE THREAD

**Issue by javnavpli** [decide-part-andarax-2/decide#185]
Aparece un error 404 Page Not Found al acceder a una votación, a pesar de que la votación haya sido creada e iniciada. El error aparece en la rama develop tras estos pasos:
1- Se despliega la rama develop
2- Se crea una votación y se inicia
3- Se intenta acceder a la vista de esa votación mediante http://localhost:8000/booth/1

**Comment by edubotdom** [comment]
He realizado pruebas y he podido comprobar como el último _merge_ a la rama develop efectuado por @danaremar y @jossanrui5 es el que causa la incidencia, ya que volviendo al estado anterior de este, funciona correctamente.

**Comment by edubotdom** [comment]
Junto con @juanogtir , he comprobado, que modificar el serializador puede ser la respuesta al problema, ya que hasta ahora, se estaba intentando parsear un atributo de QuestionOption que no existe, ya que pertenece a QuestionSerializer. Una vez modificado, funciona la vista correctamente.
``` python
class QuestionOptionSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = QuestionOption
        fields = ('number', 'option')


class QuestionSerializer(serializers.HyperlinkedModelSerializer):
    options = QuestionOptionSerializer(many=True)
    order_options = QuestionOrderSerializer(many=True)
    class Meta:
        model = Question
        fields = ('desc', 'options', 'order_options', 'is_yes_no_question')
```

**Comment by juanogtir** [comment]
Junto con @edubotdom , se ha corregido y comprobado el fallo en el QuestionSerializer que provocaba la excepción en la cabina de votación.
