### ISSUE TITLE
Error Elementos CSS  pruebas selenium Github

### ISSUE THREAD

**Issue by PabloRodriguezGarrido11** [decide-part-andarax-2/decide#195]
Al realizar la ejecución de las pruebas en local da errores a la hora de encontrar ciertos elementos css. He estado revisando y generando el código mediante selenium varias veces pero sigue sin encontrarlos.

Para ejecutar las pruebas hay que introducir el comando:

``` ./manage.py test autheticacion/test_github.py ```

**Comment by julsoutos** [comment]
Este error se surge por el tiempo de carga que hay entre las diferentes redirecciones que se realizan hasta llegar a la página donde busca el elemento css. El error se ha solucionado introduciendo la función ``` time.sleep(4) ``` antes de la línea de código que busca el elemento, es decir, selenium se espera 4 segundos hasta ejecutar la línea, por lo que le da tiempo de cargar.

**Comment by PabloRodriguezGarrido11** [comment]
Perfecto, se ha solucionado poniendo esa función después de cada redirección.
