### ISSUE TITLE
Error al hacer start de una Voting en Docker

### ISSUE THREAD

**Issue by julsoutos** [decide-part-andarax-2/decide#196]
Al darle a Start a una Voting que acabamos de crear desde admin, cuando el sistema está desplegado en Docker, da error.

Se ha generado en un navegador cualquiera y se han seguido los siguientes pasos:
1.- Clonamos la rama develop.
2.- Nos movemos a la carpeta decide/docker.
3.- Ejecutamos el comando ```docker-compose up```.
4.- Creamos un usuario admin con el comando ```docker exec -ti decide_web python3 ./manage.py createsuperuser```.
5.- Nos dirigimos a la url localhost:8000/admin, iniciamos sesión con las credenciales anteriores y creamos una Voting (con auth http://localhost:8000).
6.- Se guarda correctamente pero al hacer Start salta error.

La traza de error es la siguiente: requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /mixnet/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4968018e10>: Failed to establish a new connection: [Errno 111] Connection refused'))

Probablemente el fallo se encuentre en el auth.

**Comment by PabloRodriguezGarrido11** [comment]
Efectivamente, el error se encuentra en que el auth debe ser "http://localhost:5000", porque ahí es donde realmente esta escuchando Docker.

**Comment by julsoutos** [comment]
Cierto, acabo de probarlo y era eso. Ahora sí funciona correctamente.
