### ISSUE TITLE
Error puerto en despliegue docker

### ISSUE THREAD

**Issue by PabloRodriguezGarrido11** [decide-part-andarax-2/decide#197]
En las diferentes redirecciones realizadas al completar las autenticaciones, docker no introduce el puerto en el que se despliega en las diferentes url de callback para volver a la votación inicial.

**Comment by julsoutos** [comment]
Se está probado con distintas configuraciones en el docker-compose.yml

**Comment by julsoutos** [comment]
Finalmente se han solucionado todos los errores, cambiando configuraciones y una vista, como se puede observar en este [commit ](https://github.com/decide-part-andarax-2/decide/commit/b3f1a52a69c10fcc8e330b79473bcfdd854fe0e7).
