### ISSUE TITLE
Fallo en Travis CI

### ISSUE THREAD

**Issue by julsoutos** [decide-part-andarax-2/decide#69]
Se produce un fallo al intentar hace cualquier build en Travis.

El error se produce en cualquier navegador. Se han seguido los siguientes pasos:

1.- Entramos en [Travis](https://travis-ci.com/) con nuestras credenciales.
2.- Nos metemos en el apartado de nuestra organización, correspondiente a nuestro repositorio.
3.- Aparece un mensaje de error: Builds have been temporarily disabled for public repositories due to a negative credit balance. Please go to the Plan page to replenish your credit balance or alter your Consume paid credits for OSS setting.

El error debe ser porque hemos consumido los créditos que teníamos disponibles en Travis. Una posible solución sería cambiar el plan actual.

**Comment by edubotdom** [comment]
Tras haber mantenido una reunión informal con los miembros con mayor responsabilidad del proyecto, en representación de sus compañeros, hemos examinado las diferentes opciones que tenemos disponibles. De momento, y para obtener asesoramiento tutorizado, he remitido un mensaje al tutor del proyecto para hacerle conocer nuestra situación y proponerle las posibles soluciones que hemos planteado.

**Comment by edubotdom** [comment]
Tras haber recibido respuesta del tutor del proyecto, nos ha comunicado dos posibles soluciones, a este problema, siendo cuestión de los miembros del equipo de desarrollo tomar una decisión.

- Esperar a que se renueven los créditos.
- Transferir la propiedad del repositorio, o cambiarlo.

Consideramos que la primera opción es inviable, por una cuestión organizativa y de fechas de cumplimiento y no podemos detener el proceso de desarrollo, por lo que nos vemos obligados a tomar la segunda opción. La mejor decisión será tomada tras haber sido estudiada entre todos, mediante procedimientos relacionados con reuniones.

**Comment by edubotdom** [comment]
Tras haber realizado la migración del repositorio de forma exitosa, he integrado Travis CI y Codacy, de nuevo, para volver a contar con las herramientas plenamente operativas tras haberlas probado.

Sugiero cerrar la incidencia.

**Comment by julsoutos** [comment]
Se ha comprobado que funciona correctamente Travis de nuevo y por ello se cierra la incidencia y se considera solucinada.
